2022-01-20 16:58:38,873 ERROR rest_utils.py:build_response:60  Response: 201 Success {'non_field_errors': ['Success']} None
2022-01-20 16:58:38,878 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 Success {'non_field_errors': ['Success']} None
2022-01-20 17:20:55,711 ERROR rest_utils.py:build_response:60  Response: 400 'firstName' {'non_field_errors': ["'firstName'"]} None
2022-01-20 17:20:55,711 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'firstName' {'non_field_errors': ["'firstName'"]} None
2022-01-20 17:22:21,841 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:22:21,841 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:23:13,445 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:23:13,445 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:31:20,107 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:31:20,107 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:33:40,540 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:33:40,540 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 17:55:15,779 ERROR rest_utils.py:build_response:60  Response: 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 17:55:15,780 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 17:56:53,701 ERROR rest_utils.py:build_response:60  Response: 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 17:56:53,701 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 17:58:24,755 ERROR rest_utils.py:build_response:60  Response: 500 Internal server error {'non_field_errors': ['Got a `TypeError` when calling `Verification.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Verification.objects.create()`. You may need to make the field read-only, or override the DocumentUploadSerializer.create() method to handle this correctly.\nOriginal exception was:\n Traceback (most recent call last):\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/query.py", line 455, in create\n    obj = self.model(**kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/base.py", line 507, in __init__\n    raise TypeError("%s() got an unexpected keyword argument \'%s\'" % (cls.__name__, kwarg))\nTypeError: Verification() got an unexpected keyword argument \'context\'\n']} None
2022-01-20 17:58:24,755 DEBUG rest_utils.py:build_response:77  Response: 200 OK 500 Internal server error {'non_field_errors': ['Got a `TypeError` when calling `Verification.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Verification.objects.create()`. You may need to make the field read-only, or override the DocumentUploadSerializer.create() method to handle this correctly.\nOriginal exception was:\n Traceback (most recent call last):\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/query.py", line 455, in create\n    obj = self.model(**kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/base.py", line 507, in __init__\n    raise TypeError("%s() got an unexpected keyword argument \'%s\'" % (cls.__name__, kwarg))\nTypeError: Verification() got an unexpected keyword argument \'context\'\n']} None
2022-01-20 17:59:49,399 ERROR rest_utils.py:build_response:60  Response: 500 Internal server error {'non_field_errors': ['Got a `TypeError` when calling `Verification.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Verification.objects.create()`. You may need to make the field read-only, or override the DocumentUploadSerializer.create() method to handle this correctly.\nOriginal exception was:\n Traceback (most recent call last):\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/query.py", line 455, in create\n    obj = self.model(**kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/base.py", line 507, in __init__\n    raise TypeError("%s() got an unexpected keyword argument \'%s\'" % (cls.__name__, kwarg))\nTypeError: Verification() got an unexpected keyword argument \'context\'\n']} None
2022-01-20 17:59:49,399 DEBUG rest_utils.py:build_response:77  Response: 200 OK 500 Internal server error {'non_field_errors': ['Got a `TypeError` when calling `Verification.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Verification.objects.create()`. You may need to make the field read-only, or override the DocumentUploadSerializer.create() method to handle this correctly.\nOriginal exception was:\n Traceback (most recent call last):\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/query.py", line 455, in create\n    obj = self.model(**kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/base.py", line 507, in __init__\n    raise TypeError("%s() got an unexpected keyword argument \'%s\'" % (cls.__name__, kwarg))\nTypeError: Verification() got an unexpected keyword argument \'context\'\n']} None
2022-01-20 18:00:28,758 ERROR rest_utils.py:build_response:60  Response: 500 Internal server error {'non_field_errors': ['Got a `TypeError` when calling `Verification.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Verification.objects.create()`. You may need to make the field read-only, or override the DocumentUploadSerializer.create() method to handle this correctly.\nOriginal exception was:\n Traceback (most recent call last):\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/query.py", line 455, in create\n    obj = self.model(**kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/base.py", line 507, in __init__\n    raise TypeError("%s() got an unexpected keyword argument \'%s\'" % (cls.__name__, kwarg))\nTypeError: Verification() got an unexpected keyword argument \'context\'\n']} None
2022-01-20 18:00:28,759 DEBUG rest_utils.py:build_response:77  Response: 200 OK 500 Internal server error {'non_field_errors': ['Got a `TypeError` when calling `Verification.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Verification.objects.create()`. You may need to make the field read-only, or override the DocumentUploadSerializer.create() method to handle this correctly.\nOriginal exception was:\n Traceback (most recent call last):\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/query.py", line 455, in create\n    obj = self.model(**kwargs)\n  File "/home/deep/Live-Projects/snv_backend/snv/env/lib/python3.9/site-packages/django/db/models/base.py", line 507, in __init__\n    raise TypeError("%s() got an unexpected keyword argument \'%s\'" % (cls.__name__, kwarg))\nTypeError: Verification() got an unexpected keyword argument \'context\'\n']} None
2022-01-20 18:04:36,905 ERROR rest_utils.py:build_response:60  Response: 500 Internal server error {'non_field_errors': ["name 'Verification' is not defined"]} None
2022-01-20 18:04:36,906 DEBUG rest_utils.py:build_response:77  Response: 200 OK 500 Internal server error {'non_field_errors': ["name 'Verification' is not defined"]} None
2022-01-20 18:06:44,000 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:06:44,000 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:07:21,293 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:07:21,293 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:07:50,495 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:07:50,496 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:08:03,327 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:08:03,328 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:10:42,371 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:10:42,372 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:18:29,329 ERROR rest_utils.py:build_response:60  Response: 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:18:29,329 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 Object of type InMemoryUploadedFile is not JSON serializable {'non_field_errors': ['Object of type InMemoryUploadedFile is not JSON serializable']} None
2022-01-20 18:20:47,473 ERROR rest_utils.py:build_response:60  Response: 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:20:47,474 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:22:52,258 ERROR rest_utils.py:build_response:60  Response: 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:22:52,258 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:22:52,398 ERROR rest_utils.py:build_response:60  Response: 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:22:52,398 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:22:54,250 ERROR rest_utils.py:build_response:60  Response: 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:22:54,251 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'content' {'non_field_errors': ["'content'"]} None
2022-01-20 18:28:20,962 ERROR rest_utils.py:build_response:60  Response: 201 uploaded {'non_field_errors': ['uploaded']} None
2022-01-20 18:28:20,962 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 uploaded {'non_field_errors': ['uploaded']} None
2022-01-20 18:32:07,496 ERROR rest_utils.py:build_response:60  Response: 400 'NoneType' object is not subscriptable {'non_field_errors': ["'NoneType' object is not subscriptable"]} None
2022-01-20 18:32:07,497 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'NoneType' object is not subscriptable {'non_field_errors': ["'NoneType' object is not subscriptable"]} None
2022-01-20 18:33:05,225 ERROR rest_utils.py:build_response:60  Response: 400 'NoneType' object is not subscriptable {'non_field_errors': ["'NoneType' object is not subscriptable"]} None
2022-01-20 18:33:05,225 DEBUG rest_utils.py:build_response:77  Response: 200 OK 400 'NoneType' object is not subscriptable {'non_field_errors': ["'NoneType' object is not subscriptable"]} None
2022-01-20 18:36:15,764 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:36:15,764 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:37:00,233 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:37:00,234 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:39:13,901 ERROR rest_utils.py:build_response:60  Response: 201 Success {'non_field_errors': ['Success']} None
2022-01-20 18:39:13,902 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 Success {'non_field_errors': ['Success']} None
2022-01-20 18:39:48,242 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:39:48,243 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:41:38,775 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:41:38,776 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:43:30,215 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:43:30,215 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:46:04,549 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:46:04,551 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:52:20,768 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:52:20,769 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:53:22,867 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:53:22,869 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:54:04,216 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:54:04,217 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 18:57:22,367 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 18:57:22,367 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 19:04:23,472 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 19:04:23,473 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
2022-01-20 19:05:15,915 ERROR rest_utils.py:build_response:60  Response: 201 success {'non_field_errors': ['success']} None
2022-01-20 19:05:15,915 DEBUG rest_utils.py:build_response:77  Response: 200 OK 201 success {'non_field_errors': ['success']} None
