2022-01-01 09:54:18,261 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User OTP successfully send None None
2022-01-01 09:54:45,646 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User created successfully None None
2022-01-01 09:59:26,245 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User OTP successfully send None None
2022-01-01 10:02:53,361 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User Successfully Login None None
2022-01-01 10:03:01,264 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User Successfully Login None None
2022-01-01 10:07:24,129 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:07:24,130 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:08:14,896 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:08:14,896 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:09:00,363 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:09:00,363 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:09:01,579 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:09:01,583 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'name'"]} None
2022-01-01 10:09:16,834 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User Successfully Login None None
2022-01-01 10:15:21,934 ERROR rest_utils.py:build_response:61  Response: 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 10:15:21,934 DEBUG rest_utils.py:build_response:78  Response: 200 OK 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 10:15:36,887 ERROR rest_utils.py:build_response:61  Response: 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 10:15:36,887 DEBUG rest_utils.py:build_response:78  Response: 200 OK 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 10:16:44,248 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User OTP successfully send None None
2022-01-01 10:17:03,175 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User Successfully Login None None
2022-01-01 10:17:24,019 ERROR rest_utils.py:build_response:61  Response: 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 10:17:24,020 DEBUG rest_utils.py:build_response:78  Response: 200 OK 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 11:17:24,015 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User OTP successfully send None None
2022-01-01 11:17:48,792 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User Successfully Login None None
2022-01-01 11:21:52,937 ERROR rest_utils.py:build_response:61  Response: 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 11:21:52,938 DEBUG rest_utils.py:build_response:78  Response: 200 OK 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 11:31:32,893 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["name 'User' is not defined"]} None
2022-01-01 11:31:32,893 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["name 'User' is not defined"]} None
2022-01-01 11:32:22,053 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'AnonymousUser' object has no attribute '_meta'"]} None
2022-01-01 11:32:22,054 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'AnonymousUser' object has no attribute '_meta'"]} None
2022-01-01 11:35:58,290 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User OTP successfully send None None
2022-01-01 11:38:43,810 ERROR rest_utils.py:build_response:61  Response: 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
2022-01-01 11:38:43,811 DEBUG rest_utils.py:build_response:78  Response: 200 OK 400 Failed {'non_field_errors': [ErrorDetail(string='Invalid OTP', code='invalid')]} None
